name: Qt CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Install Qt
        - uses: jurplel/install-qt-action@v2
