name: Qt CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
    - uses: jurplel/install-qt-action@v2.13.0
    - with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}/example/'
        install-deps: 'true'
        modules: 'qtcharts qtwebengine'
        cached: 'false'
        setup-python: 'true'
        tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
        set-env: 'false'
        tools-only: 'false'
        aqtversion: '==1.1.3'
        py7zrversion: '==0.14.0'
        extra: '--external 7z'
